from forex_python.converter import CurrencyRates

print('---CURRENCY CONVERTER---')
print('\nAvailable currencies')
print('----------------------')
#print("Mauritian Rupee: MUR")
print("United States Dollar: USD")
print("Euro: EUR")
print("British Pound Sterling: GBP")
print("Japanese Yen: JPY")
print("Canadian Dollar: CAD")
print("Australian Dollar: AUD")
print("Swiss Franc: CHF")
print("Chinese Yuan Renminbi: CNY")
print("Indian Rupee: INR")
print("Brazilian Real: BRL")
print("South African Rand: ZAR")
print("Russian Ruble: RUB")
print("Mexican Peso: MXN")
print("Singapore Dollar: SGD")
print("New Zealand Dollar: NZD")
print("Hong Kong Dollar: HKD")
print("Norwegian Krone: NOK")
print("Swedish Krona: SEK")
print("South Korean Won: KRW")
print("Turkish Lira: TRY")
print("Indonesian Rupiah: IDR")
print("Argentine Peso: ARS")
print("Saudi Riyal: SAR")
print("United Arab Emirates Dirham: AED")

conv = CurrencyRates()
amount_to_be_converted = float(input("\nEnter the amount: "))
from_currency = input("\nFrom which currency?(USD|EUR...) ").upper()
to_currency = input("To which currency?(USD|EUR...) ") .upper()
print(from_currency,amount_to_be_converted,"To",to_currency)
converted_amount = conv.convert(from_currency,to_currency, amount_to_be_converted)
print('------------------')
print(converted_amount, to_currency)